version: "3"

services:
  python:
    image: beammodel/beam-competition:accessibility-0.0.1
    command:
      - sh
      - -c
      - 'while sleep 3600; do :; done'
    volumes:
      - ./tmp-data:/tmp-data


  scala:
    image: beammodel/beam-competition:0.0.1-SNAPSHOT
    depends_on:
      - python
    entrypoint:
      - /competitions/bin/competitions
      - --scenario
      - "sioux_faux"
      - --sample-size
      - "1k"
      - --iters
      - "1"
    volumes:
      - ./tmp-data:/tmp-data
      - ./submission-inputs:/submission-inputs
      - ./output:/output
      - /var/run/docker.sock:/var/run/docker.sock
